// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdsjuwicunlswwsonhao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkc2p1d2ljdW5sc3d3c29uaGFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTQ4NDQsImV4cCI6MjA2OTM3MDg0NH0.a43dxALxZVYObwT01vUPJjqDMU0TTt6J0je0oqIHyHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});